version: '2'
volumes:
    grafana-data:
services:
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'grafana-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
